#!/bin/sh /etc/rc.common
. /usr/share/libubox/jshn.sh
. /lib/functions.sh

START=96
USE_PROCD=1
FWXD_BIN="/usr/bin/fwxd"
FEATURE_FILE="/tmp/feature.cfg"

stop_service(){
	killall -9 fwxd
	killall -9 rule_manager
}

start_service(){
	lsmod |grep "fwx " >/dev/null
	if [ $? -ne 0 ];then
		modprobe fwx
	fi

	test -f $FEATURE_FILE &&{
		rm $FEATURE_FILE
	}

	ln -s /etc/fwxd/feature.cfg $FEATURE_FILE
	procd_open_instance
	procd_set_param respawn 60 5 5
	procd_set_param stderr 1
	procd_set_param command "$FWXD_BIN"
	procd_close_instance
	
	procd_open_instance
	procd_set_param respawn 60 5 5
	procd_set_param stderr 1
	procd_set_param command "/usr/bin/rule_manager"
	procd_close_instance
}
